# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker golang python pyenv poetry helm kubectl kube-ps1)
source $ZSH/oh-my-zsh.sh

# Add poetry bin to path
export PATH="/$HOME/.local/bin:$PATH"

# By default ubuntu apt install go in user dir
export PATH="/$HOME/go/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Change username to local username
DEFAULT_USER="devalv"

alias df="duf -only local -only-fs ext4,ntfs,fat32"
alias la="exa -l --no-permissions --group-directories-first"
alias cat="bat"
alias vim="nvim"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
